# Generated by Django 2.1.4 on 2019-01-29 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import scraping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.CharField(default=datetime.date(2019, 1, 29), max_length=200, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tomorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=16)),
                ('info', models.CharField(max_length=64)),
                ('rain', models.CharField(max_length=64)),
                ('temp_min', models.CharField(max_length=4)),
                ('temp_max', models.CharField(max_length=4)),
                ('target', models.ForeignKey(default=scraping.models.get_or_create_date, on_delete=django.db.models.deletion.CASCADE, to='scraping.Date')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=4)),
                ('temperature', models.CharField(max_length=8)),
                ('precipitation', models.CharField(max_length=4)),
                ('wind_blow', models.CharField(max_length=4)),
                ('wind_speed', models.CharField(max_length=4)),
                ('day_length', models.CharField(max_length=4)),
                ('target', models.ForeignKey(default=scraping.models.get_or_create_date, on_delete=django.db.models.deletion.CASCADE, to='scraping.Date')),
            ],
        ),
    ]
