# Generated by Django 2.1.4 on 2019-01-30 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='pub_date',
            field=models.CharField(default=datetime.date(2019, 1, 30), max_length=200, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tomorrow',
            name='temp_min',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
