# Generated by Django 2.1.4 on 2019-01-29 15:59

from django.db import migrations, models
import django.db.models.deletion
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20190129_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='weatherdetail',
            name='target',
            field=models.ForeignKey(default=scraping.models.get_or_create_date, on_delete=django.db.models.deletion.CASCADE, to='scraping.Date'),
        ),
    ]
