# Generated by Django 2.1.4 on 2019-01-31 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20190130_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='pub_date',
            field=models.CharField(default=datetime.date(2019, 1, 31), max_length=200, verbose_name='date published'),
        ),
    ]
