# Generated by Django 2.1.2 on 2018-11-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrimap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
