# Generated by Django 2.1.3 on 2018-12-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agrimap', '0002_auto_20181112_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='latlng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(unique=True)),
                ('lng', models.IntegerField(unique=True)),
            ],
        ),
    ]
