# Generated by Django 2.1.4 on 2019-01-23 05:01

from django.db import migrations, models
import django.utils.timezone
import register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('example1', models.CharField(blank=True, max_length=150, verbose_name='example1')),
                ('example2', models.CharField(blank=True, max_length=150, verbose_name='example2')),
                ('example3', models.CharField(blank=True, max_length=150, verbose_name='example3')),
                ('pulldown', models.CharField(blank=True, choices=[('', '選択肢から選んでください'), ('ほうれん草', 'ほうれん草'), ('白菜', '白菜'), ('トマト', 'トマト'), ('たまねぎ', '玉ねぎ'), ('ナス', 'ナス'), ('ネギ', 'ネギ'), ('ジャガイモ', 'ジャガイモ'), ('きのこ', 'きのこ'), ('にんじん', 'にんじん'), ('だいこん', 'だいこん'), ('かぼちゃ', 'かぼちゃ'), ('きゅうり', 'きゅうり'), ('ブロッコリー', 'ブロッコリー'), ('ピーマン', 'ピーマン'), ('キャベツ', 'キャベツ'), ('米', '米'), ('麦', '麦'), ('イチゴ', 'イチゴ'), ('カボス', 'カボス'), ('みかん', 'みかん'), ('梨', '梨'), ('ぶどう', 'ぶどう'), ('キウイ', 'キウイ'), ('その他', 'その他')], max_length=150, verbose_name='pulldown')),
                ('lat', models.CharField(blank=True, max_length=150, verbose_name='lat')),
                ('lng', models.CharField(blank=True, max_length=150, verbose_name='lng')),
                ('geo', models.CharField(blank=True, max_length=150, verbose_name='geo')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', register.models.UserManager()),
            ],
        ),
    ]
