# Generated by Django 2.1.4 on 2018-12-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='example1',
            field=models.CharField(blank=True, max_length=150, verbose_name='example1'),
        ),
        migrations.AddField(
            model_name='user',
            name='example2',
            field=models.CharField(blank=True, max_length=150, verbose_name='example2'),
        ),
        migrations.AddField(
            model_name='user',
            name='example3',
            field=models.CharField(blank=True, max_length=150, verbose_name='example3'),
        ),
    ]
