# Generated by Django 2.1.4 on 2019-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='HN',
            field=models.CharField(blank=True, max_length=150, verbose_name='ユーザ名'),
        ),
    ]
