# Generated by Django 2.1.4 on 2019-01-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20181229_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='select',
            field=models.CharField(blank=True, max_length=150, verbose_name='select'),
        ),
    ]
