# Generated by Django 2.1.4 on 2019-01-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='select',
        ),
        migrations.AddField(
            model_name='user',
            name='pulldown',
            field=models.CharField(blank=True, choices=[('', '選択肢から選んでください><'), ('0', 'バナナ'), ('1', 'オレンジ'), ('2', 'ぶどう'), ('3', 'はくさい'), ('4', 'ちんこ'), ('5', 'ぶどうんこ'), ('6', 'おせちんこ'), ('7', 'なす'), ('8', 'こめ'), ('9', 'むぎ'), ('10', 'きゃべつ'), ('11', 'たまねぎ'), ('12', 'その他')], max_length=150, verbose_name='pulldown'),
        ),
    ]
