# Generated by Django 2.1.4 on 2019-01-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190121_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pulldown',
            field=models.CharField(blank=True, choices=[('', '選択肢から選んでください><'), ('バナナ', 'バナナ'), ('オレンジ', 'オレンジ'), ('ぶどう', 'ぶどう'), ('はくさい', 'はくさい'), ('ちんこ', 'ちんこ'), ('ぶどうんこ', 'ぶどうんこ'), ('おせちんこ', 'おせちんこ'), ('なす', 'なす'), ('こめ', 'こめ'), ('むぎ', 'むぎ'), ('きゃべつ', 'きゃべつ'), ('たまねぎ', 'たまねぎ'), ('その他', 'その他')], max_length=150, verbose_name='pulldown'),
        ),
    ]
