# Generated by Django 2.1.4 on 2019-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_user_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pulldown',
            field=models.CharField(blank=True, choices=[('', '選択肢から選んでください'), ('ほうれん草', 'ほうれん草'), ('白菜', '白菜'), ('トマト', 'トマト'), ('たまねぎ', '玉ねぎ'), ('ナス', 'ナス'), ('ネギ', 'ネギ'), ('ジャガイモ', 'ジャガイモ'), ('きのこ', 'きのこ'), ('にんじん', 'にんじん'), ('だいこん', 'だいこん'), ('かぼちゃ', 'かぼちゃ'), ('きゅうり', 'きゅうり'), ('ブロッコリー', 'ブロッコリー'), ('ピーマン', 'ピーマン'), ('キャベツ', 'キャベツ'), ('米', '米'), ('麦', '麦'), ('イチゴ', 'イチゴ'), ('カボス', 'カボス'), ('みかん', 'みかん'), ('梨', '梨'), ('ぶどう', 'ぶどう'), ('キウイ', 'キウイ'), ('その他', 'その他')], max_length=150, verbose_name='pulldown'),
        ),
    ]
