# Generated by Django 2.1.3 on 2018-12-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_publick',
            new_name='is_public',
        ),
        migrations.AlterField(
            model_name='reply',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
